// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gmewenwayiiaxhujkubu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdtZXdlbndheWlpYXhodWprdWJ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2MTk4NjEsImV4cCI6MjA3MjE5NTg2MX0.8GNA6p4P_Aoh_9cWfnGvvqH0LyOyvePfMIPnF92EI6E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});